# Site settings
title: "Amanda's Personal Website"
description: "Trying things out."
author: Amanda K
email: akkis@ou.edu
baseurl: ""
logo: /assets/img/cat.jpg
permalink: /:title

#github:
#  is_user_page: false

# Build settings
theme: jekyll-theme-minimal
