# Site settings
title: Great New Blog Title
author: Amanda K
email: akkis@ou.edu
logo: /assets/img/cat.jpg
description: "Trying things out."

github:
  is_user_page: false

# Build settings
theme: jekyll-theme-minimal
