# Site settings
title: "Amanda's Personal Website"
description: "Trying things out."
author: Amanda K
email: akkis@ou.edu
logo: /assets/img/cat.jpg
permalink: /:categories/:title
paginate: 1
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# GitHub settings
is_user_page: true
is_project_page: false
show_downloads: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Build settings
remote_theme: pages-themes/minimal@v0.2.0

# Serve settings
#detach: true
